// Code generated by hertz generator.

package main

import (
	"dous/biz/model/query"
	"github.com/cloudwego/hertz/pkg/app/server"
)

func main() {
	h := server.Default()
	//dsn := "root:cjy12345@(127.0.0.1:3306)/douy?charset=utf8mb4&parseTime=True&loc=Local"
	//query.SetDefault(model.ConnectDB(dsn))
	//init()
	Init()
	query.SetDefault(DB)
	register(h)
	h.Spin()
}
