// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package orm_gen

import (
	"time"
)

const TableNameComment = "comments"

// Comment mapped from table <comments>
type Comment struct {
	ID          int64     `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id,string"`
	UserID      int64     `gorm:"column:user_id;type:int" json:"user_id"`
	VideoID     int64     `gorm:"column:video_id;type:int" json:"video_id"`
	CommentText string    `gorm:"column:comment_text;type:varchar(255)" json:"comment_text"`
	CreatDate   time.Time `gorm:"column:creat_date;type:datetime" json:"creat_date"`
	Cancel      int64     `gorm:"column:cancel;type:int" json:"cancel"`
}

// TableName Comment's table name
func (*Comment) TableName() string {
	return TableNameComment
}
