// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package orm_gen

const TableNameFollow = "follows"

// Follow mapped from table <follows>
type Follow struct {
	ID         int64 `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id,string"`
	UserID     int64 `gorm:"column:user_id;type:int" json:"user_id"`
	FollowerID int64 `gorm:"column:follower_id;type:int" json:"follower_id"`
	Cancel     int64 `gorm:"column:cancel;type:int" json:"cancel"`
}

// TableName Follow's table name
func (*Follow) TableName() string {
	return TableNameFollow
}
