// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package orm_gen

const TableNameLike = "likes"

// Like mapped from table <likes>
type Like struct {
	ID      int64 `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id,string"`
	UserID  int64 `gorm:"column:user_id;type:int" json:"user_id"`
	VideoID int64 `gorm:"column:video_id;type:int" json:"video_id"`
	Cancel  int64 `gorm:"column:cancel;type:int" json:"cancel"`
}

// TableName Like's table name
func (*Like) TableName() string {
	return TableNameLike
}
