// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package orm_gen

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	Username string `gorm:"column:username;type:varchar(255)" json:"username"`
	ID       int64  `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id,string"`
	Password string `gorm:"column:password;type:varchar(255)" json:"password"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
