// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package orm_gen

import (
	"time"
)

const TableNameVideo = "videos"

// Video mapped from table <videos>
type Video struct {
	ID       int64     `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id,string"`
	AuthorID int64     `gorm:"column:author_id;type:int" json:"author_id"`
	PlayURL  string    `gorm:"column:play_url;type:varchar(255)" json:"play_url"`
	CoverURL string    `gorm:"column:cover_url;type:varchar(255)" json:"cover_url"`
	Time     time.Time `gorm:"column:time;type:datetime" json:"time"`
	Title    string    `gorm:"column:title;type:varchar(255)" json:"title"`
}

// TableName Video's table name
func (*Video) TableName() string {
	return TableNameVideo
}
